/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authenticatedProfileRouteImport } from './routes/(authenticated)/profile'
import { Route as authenticatedProductsRouteImport } from './routes/(authenticated)/products'
import { Route as authenticatedCartRouteImport } from './routes/(authenticated)/cart'
import { Route as authenticatedProductsIndexRouteImport } from './routes/(authenticated)/products.index'
import { Route as authenticatedProductsIdRouteImport } from './routes/(authenticated)/products.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedProfileRoute = authenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedProductsRoute = authenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedCartRoute = authenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedProductsIndexRoute =
  authenticatedProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedProductsRoute,
  } as any)
const authenticatedProductsIdRoute = authenticatedProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => authenticatedProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cart': typeof authenticatedCartRoute
  '/products': typeof authenticatedProductsRouteWithChildren
  '/profile': typeof authenticatedProfileRoute
  '/products/$id': typeof authenticatedProductsIdRoute
  '/products/': typeof authenticatedProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cart': typeof authenticatedCartRoute
  '/profile': typeof authenticatedProfileRoute
  '/products/$id': typeof authenticatedProductsIdRoute
  '/products': typeof authenticatedProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(authenticated)/cart': typeof authenticatedCartRoute
  '/(authenticated)/products': typeof authenticatedProductsRouteWithChildren
  '/(authenticated)/profile': typeof authenticatedProfileRoute
  '/(authenticated)/products/$id': typeof authenticatedProductsIdRoute
  '/(authenticated)/products/': typeof authenticatedProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cart'
    | '/products'
    | '/profile'
    | '/products/$id'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/cart' | '/profile' | '/products/$id' | '/products'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/login'
    | '/(authenticated)/cart'
    | '/(authenticated)/products'
    | '/(authenticated)/profile'
    | '/(authenticated)/products/$id'
    | '/(authenticated)/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/profile': {
      id: '/(authenticated)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authenticatedProfileRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/products': {
      id: '/(authenticated)/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof authenticatedProductsRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/cart': {
      id: '/(authenticated)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof authenticatedCartRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/products/': {
      id: '/(authenticated)/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof authenticatedProductsIndexRouteImport
      parentRoute: typeof authenticatedProductsRoute
    }
    '/(authenticated)/products/$id': {
      id: '/(authenticated)/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof authenticatedProductsIdRouteImport
      parentRoute: typeof authenticatedProductsRoute
    }
  }
}

interface authenticatedProductsRouteChildren {
  authenticatedProductsIdRoute: typeof authenticatedProductsIdRoute
  authenticatedProductsIndexRoute: typeof authenticatedProductsIndexRoute
}

const authenticatedProductsRouteChildren: authenticatedProductsRouteChildren = {
  authenticatedProductsIdRoute: authenticatedProductsIdRoute,
  authenticatedProductsIndexRoute: authenticatedProductsIndexRoute,
}

const authenticatedProductsRouteWithChildren =
  authenticatedProductsRoute._addFileChildren(
    authenticatedProductsRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedCartRoute: typeof authenticatedCartRoute
  authenticatedProductsRoute: typeof authenticatedProductsRouteWithChildren
  authenticatedProfileRoute: typeof authenticatedProfileRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedCartRoute: authenticatedCartRoute,
  authenticatedProductsRoute: authenticatedProductsRouteWithChildren,
  authenticatedProfileRoute: authenticatedProfileRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
